# Generated by Django 3.2.2 on 2021-05-27 10:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesnews',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
