# Generated by Django 3.2.2 on 2021-05-27 10:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0002_alter_tablesnews_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesnews',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
